In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2])
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[0 1 2]
int32


In [3]:
b = np.array([1, 1.5, 2])
print(b)
print(b.dtype)

c = np.array([1 + 2j, 3 + 4j, 5 + 6j])
print(c)
print(c.dtype)

d = np.array([True, False, True, False, False])
print(d)
print(d.dtype)

e = np.array(list("TellusxData"))
print(e)
print(e.dtype)

[1.  1.5 2. ]
float64
[1.+2.j 3.+4.j 5.+6.j]
complex128
[ True False  True False False]
bool
['T' 'e' 'l' 'l' 'u' 's' 'x' 'D' 'a' 't' 'a']
<U1


In [4]:
f = np.array([100, 200, 300], dtype = np.int16)
print(f)
print(f.dtype)

[100 200 300]
int16


In [5]:
g = np.array([1.5, 2.5, 3.5])
print(g)
print(g.dtype)

[1.5 2.5 3.5]
float64


In [6]:
g = g.astype(np.int64)
print(g)
print(g.dtype)

[1 2 3]
int64


In [10]:
d = np.linspace(0, 10, 2)
print(d)

[ 0. 10.]


In [11]:
e = np.empty(5)
print(e)

[ 0.   2.5  5.   7.5 10. ]


In [12]:
f = np.zeros(5)
print(f)

[0. 0. 0. 0. 0.]


In [17]:
g = np.random.rand(5)
print(g)

[0.17379678 0.86397933 0.86796773 0.74594951 0.8058214 ]


In [18]:
g = g * 6 + 1
g = g.astype(np.int8)
print(g)

[2 6 6 5 5]


In [20]:
h = np.arange(1, 4)
i = np.arange(4, 7)
j = np.concatenate([h, i])
print(j)

[1 2 3 4 5 6]


In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [22]:
a = np.empty((2, 3), dtype=np.int64)
a[0] = [1, 2, 3]
a[1] = [4, 5, 6]

print(a)

[[1 2 3]
 [4 5 6]]


In [23]:
a = np.arange(1, 21)
print(a)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)


In [24]:
b = a.reshape(4, 5)
print(b)
print(b.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)


In [25]:
b2 = a.reshape(2, 2, 5)
print(b2)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [27]:
c = np.arange(1, 21).reshape(4, 5)
d = c.flatten()

print(c)
print(d)

e = c.ravel()

print(c)
print(e)
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [31]:
a = np.arange(1, 101).reshape(10, 10)
print(a[0, 0])
print(a[1, 1])
print(a[1:3, 1:3])
print(a[1:5:3, 1:5:3])

1
12
[[12 13]
 [22 23]]
[[12 15]
 [42 45]]


In [32]:
a = np.arange(1, 20)
a = np.append(a, 20)
a = np.append(a, (21, 22, 23, 24))
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [33]:
b = np.arange(1, 6)
b = np.insert(b, 1, 6)
b = np.insert(b, 3, (7, 8))
print(b)

[1 6 2 7 8 3 4 5]


In [38]:
a = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
b = np.array([1, 1, 1])

(h, v) = a.shape

c = np.insert(a, 2, b, 0)
print(c)

d = np.insert(a, h, b, 0)
print(d)

e = np.insert(a, 2, b, 1)
print(e)

f = np.insert(a, v, b, 1)
print(f)

[[0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]]
[[0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]]
[[0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]]


In [39]:
a = np.arange(5)
a = np.delete(a, 2)
print(a)

[0 1 3 4]


In [41]:
b = np.arange(1, 26).reshape(5, 5)
b = np.delete(b, 1, 0)
print(b)

c = np.arange(1, 26).reshape(5, 5)
c = np.delete(c, 1, 1)
print(c)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  3  4  5]
 [ 6  8  9 10]
 [11 13 14 15]
 [16 18 19 20]
 [21 23 24 25]]


In [43]:
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
print(a)
print(b)
print(b + a)
print(b - a)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]
[[6 6 6]
 [6 6 6]]


In [44]:
c = np.arange(1, 5).reshape(2, 2)
d = np.arange(5, 9).reshape(2, 2)

print(c)
print(d)
print()
print(c * d)
print(c / d)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [48]:
a = np.random.rand(5)
print(a)

a = a * 6 + 1
print(a)

print(np.array(np.floor(a), dtype=np.int64))
print(np.array(np.ceil(a), dtype=np.int64))
print(np.array(np.round(a), dtype=np.int64))

[0.29755993 0.10404788 0.53452271 0.98572268 0.26469298]
[2.78535957 1.62428725 4.20713623 6.91433609 2.58815789]
[2 1 4 6 2]
[3 2 5 7 3]
[3 2 4 7 3]


In [49]:
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
b = np.fliplr(a)
print(b)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [53]:
c = np.flipud(a)
print(c)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [56]:
d = np.rot90(a, 1)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 6 9]
 [2 5 8]
 [1 4 7]]


In [57]:
e = np.rot90(a, 2)
print(e)

[[9 8 7]
 [6 5 4]
 [3 2 1]]
